config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'

  get '/signup' => 'users#new'
  post '/signup' =>'users#create'

  get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
  delete '/logout' =>'sessions#destroy'

  get '/about' => 'static#about'

	# This will be removed when the users#index and accompanying features are added
	# If we use user#index, we need to include a link to that page in the nav bar
  get '/users' => 'users#new'

  get '/pets' => 'pets#index'
  get '/pets/:id' => 'pets#show'

  get '/pets/:id/like' => 'pets#like', as: :like
  get '/pets/:id/dislike' => 'pets#dislike', as: :dislike

  
  resources :users

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmler.re

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	has_many :selected_pets
	has_many :users, through: :selected_pets

	 # scope :favorite,  -> { where(is_liked: true) }

end

app/models/selected_pet.rb
class SelectedPet < ActiveRecord::Base
  belongs_to :user
  belongs_to :pet

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :selected_pets
	has_many :pets, through: :selected_pets

	before_save { self.email = email.downcase }
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	#Check if the user is logged in. True = Logged in. False = Not Logged In/No Account
 #  def session
	# 	if cookies.signed[:session_id] = self.session_id
	# 		return true
	# 	else
	# 		return false
	# 	end
	# end


	validates :email, presence: true, length: { maximum: 255 },
						format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
	
	has_secure_password
	validates :password, presence: true, length: { maximum: 50 }, allow_nil: true

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
	before_action :logged_in_user, only: [:like, :dislike]

	def index
		# In the future, we can try to paginate pages with many results with .paginate
		@pets = Pet.all
	end

	def show
		@pet = Pet.find(params[:id])
	end

	def like
			@pet = Pet.find(params[:id])
			spet = SelectedPet.new
			spet.pet_id = @pet.id
			spet.user_id = current_user.id
			spet.save
			@pet.is_liked = true
			redirect_to pets_path
	end

	# Feature to add in the future
	# def dislike
	# 	@pet = Pet.find(params[:id])
	# 	@pet.is_liked = false
	# 	redirect_to pets_path
	# end

	private

	def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     	log_in user
      redirect_back_or pets_path
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def welcome
	end

	def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user,   only: [:show,  :edit, :update]

  # Future Feature: Admin Users with ability to delete users in user index 
 #  def index
	# 	# @users = User.paginate(page: params[:page])
	# end

	def show
		@user = User.find(params[:id])
	end

	# For registering to the site
	def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to OneStopAdopt!"
      redirect_to @user
    else
      render 'new'
    end 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper

	# def heart
	# 	@selected_pet = SelectedPet.find(:id).is_liked = true
	# end


	# def unheart
	# 	@selected_pet = SelectedPet.find(:id)
	# 	@selected_pet.is_liked = false
	# end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in a given user.
	def log_in(user)
    session[:user_id] = user.id
  end

   # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!-- <nav>
    <ul>
      <li>Powered by PetFinder API</li>
    </ul>
  </nav> -->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Pets", pets_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneStopAdopt</title>
    <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pet/index.html.erb
<h1>All Pets</h1>

	<% @pets.each do |pet| %>
    <p>
  		<%= image_tag("#{pet.photo}", :size => "250x250", :crop => :fill) %>
    	<%= pet.name %>
    	<%= pet.sex %>
    	<%= pet.age %>
      <%= link_to "Pet Details", '/pets/details' %>
    </p>
  <% end %>

app/views/pets/index.html.erb
<div class="main-container">
  <h2>All Pets</h2>
    <br>
    <br>

  <div class="well bs-component" id="pet-index-flex">
      <% @pets.each do |pet| %>
        <p>
      		<%= image_tag("#{pet.photo}", :size => "250x250", :crop => :fill, :class => "animal-pic") %>
        	<br>
          <span class="pet-details">

            <%= pet.name %> <%= link_to like_path(pet.id) do %>
              <i class="fa fa-heart" aria-hidden="true"></i>
            <% end %>
            </span>
            <br>
            <span class="pet-details">
          	   <strong>Gender:</strong> <%= pet.sex %>
            </span>
            <br>
            <span class="pet-details">
          	   <strong>Age:</strong> <%= pet.age %>
            </span>
            <br>
            <span class="pet-details">
          	   <%= link_to "Pet Details", "pets/#{pet.id}" %>
            </span>
          </span>

        </p>
      <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="main-container">
  <h1>Pet Details</h1>
  <br>
    <div class="well bs-component">
      <section class="user_info">
        <h2><%= @pet.name %></h2>
        <br>
        	<%= image_tag("#{@pet.photo}", :size => "250x250", :crop => :fill, :class => "animal-pic") %>

      </section>

      <section>
        <br>
      	<h4>Pet Details</h4>
      	<strong>Gender:</strong> <%= @pet.sex %><br>
        <strong>Age:</strong> <%= @pet.age %><br>
        <strong>Breed:</strong> <%= @pet.breed %><br>
        <strong>Size:</strong> <%= @pet.size %>

        <br>
        <br>

        <h4>Description</h4>
        <%= @pet.description %>

    		<br>
        <br>

        <h4>Shelter Information:</h4>
        <%= @pet.address1 %> <%= @pet.address2 %> <%= @pet.city %>, FL <%= @pet.zip %>
        <br>
        <%= @pet.phone %>
        <br>
        <%= @pet.email %>
        

      </section>
    </div>

</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="main-container">
  <h1>Update your profile</h1>

  <div class="row">
    <div class="well bs-component">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <br>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>

      <div class="gravatar_edit">
      <br>
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank">change</a>
      </div>
    </div>
</div>

app/views/users/index.html.erb
<!-- Not activating this feature at this time. -->

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to "#{user.first_name} #{user.last_name}", user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="main-container">
<h1>Sign up</h1>

<div class="row">
  <div class="well bs-component">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>


      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="main-container">
  <div class="row">
    <aside >
      <section class="user_info">
        <h2>
          <%= gravatar_for @user %>
          <%= @user.first_name %> <%= @user.last_name %>
        </h2>
        <br>
      </section>
    </aside>
  </div>

  <h3>Your Future Friends</h3>
  <br>

  <div class="well bs-component" id="pet-flex">
      <br>
        <% current_user.selected_pets.each do | spet | %>
      		<span><%= image_tag("#{spet.pet.photo}", :size => "200x200", :crop => :fill, :class => "animal-pic") %>
          <h4><a href="#" class="pet-link"><%= spet.pet.name %></a></h4>  
          </span>
      	<% end %> 
      <br> 
  </div>
</div>